### PR TITLE
feat: add tag list to post

### PR DESCRIPTION
**Pull request by cgiax**
This adds the list of 'tags' to a post header, the tags are clickable and follow the same styling of the rest of the theme. 

This allows viewers of the post easy access to related content via the tags (if specified) without the need to click on 'Tags' and have to figure out which might be a related tag for the post they were reading.

### CODE REVIEW

**Comment by vividvilla** [comment]
Thanks for the pull request. I think its better to place these tags at the end of the article since users are more likely to find related content after they read the article and it seems like a common pattern also.

**Comment by cgiax** [comment]
Ok, cool... I will move them to the bottom, let me know what you think.

**Comment by cgiax** [comment]
@vividvilla should the tags be prefixed with a `#` like `#nodejs #javascript` or no? Some themes seem to have the hash sign in front of the tags. 

Currently the tags are placed at the bottom of the post markdown, there is no top padding and the tags just have a 5px spacing between them.

**Comment by vividvilla** [comment]
Yeah this looks odd and there is no context what it is. How about adding prefix`Tagged` like [here](https://themes.gohugo.io//theme/arabica/post/markdown-syntax/), If you have some idea let me know we can discuss that.

**Comment by cgiax** [comment]
Yeah I agree, it looks odd. I will play a bit around and see what I can come up with. In case I can open an issue for this and mark it as an 'enhancement' and this way I can share some screen shots to help us decide. If that is ok with you.

**Comment by cgiax** [comment]
@vividvilla could you check if you like this layout pls. It's still very simple and it's only for the TAGS.

I tried various things but I didn't like anything in particular except for this.

**Pull request merged**
